---
openapi: 3.0.0
info:
  title: Task API
  description: Task API Information
  contact:
    name: Blokoding
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  "/tasks":
    get:
      summary: Get all tasks
      description: Use to get all tasks
      responses:
        "200":
          description: All tasks successfully returned
        "400":
          description: Failure to get all tasks
  "/task":
    post:
      summary: Create task
      description: Use to request all tasks
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Task"
            examples:
              task:
                value:
                  job: "developpeur Java"
                  location: Issy-les-Moulineaux
                  duration: 12
                  price: 100
                  remote: 50
                  start: 12
                  context: intégration au sein de l’équipe Engineering du pôle Industrialisation
                  mission: Participer aux Comités d’Architecture pour garantir la bonne conformité des bonne pratique des APIs.
      responses:
        "200":
          description: A successfull response
        "500":
          description: Failure in creating task
  "/tasks/{id}":
    get:
      summary: Get task by id
      description: Use to request a task
      parameters:
        - in: path
          name: id
      responses:
        "200":
          description: Tasks successfully returned
        "500":
          description: Failure to download task
  "/pdf/{id}":
    get:
      summary: Get pdf task by id
      description: Use to request a task
      parameters:
        - in: path
          name: id
      responses:
        "200":
          description: Pdf successfuly downloaded
        "500":
          description: Failure to download pdf task
  "/tasks/search/keywords":
    get:
      summary: Search task by keyword
      description: Use to search a keyword in all task fields
      parameters:
        - in: query
          name: search
      responses:
        "200":
          description: Tasks search successfully returned
        "500":
          description: Fail to search tasks
  "/tasks/modify/{id}":
    patch:
      summary: Modify task by id
      description: Use to modify a task
      parameters:
        - in: path
          name: id
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Task"
            examples:
              task:
                value:
                  job: "developpeur Java"
                  location: Issy-les-Moulineaux
                  duration: 12
                  price: 100
                  remote: 50
                  start: 12
                  context: intégration au sein de l’équipe Engineering du pôle Industrialisation
                  mission: Participer aux Comités d’Architecture pour garantir la bonne conformité des bonne pratique des APIs.
      responses:
        "200":
          description: Task successfully modified
        "500":
          description: Failure to modify task
components:
  schemas:
    Task:
      type: object
      properties:
        location:
          type: string
          description: Location of the mission
          example: Issy-les-Moulineaux
        duration:
          type: number
          description: Duration of the mission
          example: 12
        price:
          type: number
          description: Price
          example: 100
        remote:
          type: number
          description: Percentage of work done remotely
          example: 50
        start:
          type: string
          description: Day the mission starts
          example: 12
        job:
          type: string
          description: Name of the job
          example: développeur ReactJs
        context:
          type: string
          description: Context
          example: intégration au sein de l’équipe Engineering du pôle Industrialisation, Cloud and Data, le consultant contribuera aux activités APIs et API Management.
        mission:
          type: string
          description: Mission
          example: Participer aux Comités d’Architecture pour garantir la bonne conformité des bonne pratique des APIs. Promouvoir les pratiques API First au sein du groupe. Rédiger Maintenir un Guideline de développement d’API (création de modèle d’API, ...)
